waypoints:
  - goal: "goal_1"
    position:
      x: 4.1    # Goal 1: x = 4.1 m, y = 0.18 m, Y = 0 deg
      y: 0.18
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0    # sin(0/2)
      w: 1.0    # cos(0/2)
  - goal: "goal_2"
    position:
      x: 9.1    # Goal 2: x = 9.1 m, y = -1.8 m, Y = 75 deg
      y: -1.8
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: 0.3826834324    # sin(75°/2)
      w: 0.9238795325    # cos(75°/2)
  - goal: "goal_3"
    position:
      x: 9.5    # Goal 3: x = 9.1 m, y = 4.1 m, Y = 35 deg
      y: 4.6
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: 0.3007057995    # sin(35°/2)
      w: 0.9537169507    # cos(35°/2)
  - goal: "goal_4"
    position:
      x: -1.15  # Goal 4: x = -1.15 m, y = 4.0 m, Y = 180 deg
      y: 4.0
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0    # sin(180°/2)
      w: 0.0    # cos(180°/2)
  - goal: "goal_5"
    position:
      x: -9.0   # Goal 5: x = -9.0 m, y = 4.0 m, Y = -90 deg
      y: 4.0
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: -0.7071067812   # sin(-90°/2)
      w: 0.7071067812    # cos(-90°/2)
  - goal: "goal_6"
    position:
      x: -9.079   # Goal 6: x = -9.1 m, y = -4.1 m, Y = 0 deg
      y: -4.098
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: 0.707   # sin(0°/2)
      w: -0.707  # cos(0°/2)
  - goal: "goal_7"
    position:
      x: -4.835    # Goal 7: x = -4.835 m, y = -3.744 m, Y = 0 deg
      y: -3.744
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0    # sin(0°/2)
      w: 1.0    # cos(0°/2)
  - goal: "goal_8"
    position:
      x: 3.8    # Goal 8: x = 3.8 m, y = -3.5 m, Y = 0 deg
      y: -3.5
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0    # sin(0°/2)
      w: 1.0    # cos(0°/2)
  - goal: "goal_9"
    position:
      x: 9.84    # Goal 9: x = 9.84 m, y = -4.6 m, Y = 180 deg
      y: -4.6
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0    # sin(180°/2)
      w: 0.0    # cos(180°/2)
  # - goal: "goal_9"
  #   position:
  #     x: 3.8519    # Goal 9: x = 9.84 m, y = -4.6 m, Y = 180 deg
  #     y: -4.66
  #     z: 0.1
  #   orientation:
  #     x: 0.0
  #     y: 0.0
  #     z: 0.0    # sin(180°/2)
  #     w: 1.0    # cos(180°/2)
